 
import './globals.css'
import { Inter } from 'next/font/google'
 import Nav from './ui/Nav'
import Footer from './ui/Footer'
 
 
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'ChildCare',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
      <Nav/>
      
    
      {children}
      <Footer/>
      </body>
    </html>
  )
}
